version: '3'

dotenv: ['.env']

env:
  KUBECONFIG: '{{.KUBECONFIG | default "./kubeconfig.yaml"}}'

includes:
  infra: ./.taskfiles/Infra.yml
  pixie: ./.taskfiles/Pixie.yml
  helm: ./.taskfiles/Helm.yml
  seccomp: ./.taskfiles/Seccomp.yml

tasks:
  default:
    cmds:
      - task --list
    silent: true

  deploy-part-1:
    desc: 'Bring up infra, deploy platform tools, install services, and start seccomp recording'
    cmds:
      - task: infra:up
      - task: seccomp:install-operator
      - task: pixie:deploy
  deploy-part-2:
    desc:
    cmds:
      - task: helm:install-all
      - task: seccomp:enable-recording
      - task: seccomp:start-recording
  pixie-collector:
    
