apiVersion: apps/v1
kind: Deployment
metadata:
  name: pixie-collector
  labels:
    app.kubernetes.io/name: pixie-collector
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: pixie-collector
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: pixie-collector
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pixie-collector
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/part-of: pixie-collector
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: otlp-grpc
              containerPort: {{ .Values.ports.grpc }}
              protocol: TCP
            - name: http
              containerPort: {{ .Values.ports.http }}
              protocol: TCP
          startupProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: otlp-grpc
            periodSeconds: 15
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
