apiVersion: v1
kind: Service
metadata:
  name: pixie-collector
  labels:
    app.kubernetes.io/name: pixie-collector
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: pixie-collector
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: otlp-grpc
      port: {{ .Values.ports.grpc }}
      targetPort: otlp-grpc
      protocol: TCP
    - name: http
      port: {{ .Values.ports.http }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: pixie-collector
    app.kubernetes.io/instance: {{ .Release.Name }}
